AM - firstName and lastName functionality added
SimpleLuke/acebook-fire pull request #4
Opened 2023-03-08 15:42 UTC by annamaggg

same as before, tests pass most of the time

2023-03-08 15:49 UTC, Perspicacity11 requested changes

2023-03-08 15:49 UTC, Perspicacity11 commented on frontend/src/components/user/SignUpForm.js
> +          <input placeholder="last Name" id="lastName" type='text' value={ lastName } onChange={handleLastNameChange} />
Just the one thing: can we capitalise 'Last'?

2023-03-08 17:06 UTC, Perspicacity11 approved these changes

2023-03-09 09:56 UTC, SimpleLuke approved these changes
Nicely done! All test pass and code is clean and clear.
It would be great if some console.log can be removed after the debugging process.
Thank you for your hard work!

2023-03-09 10:14 UTC, merged